version: "3.8"

services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: psql12alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - backupdata:/var/tmp

volumes:
  dbdata:
  backupdata: