version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata: